# Makefile
SOURCE		= ./src/main.c
PROJECT 	= 00_Blink
DEVICE 		= atmega328p
PROGRAMMER 	= arduino

default: build

build : clean
	@mkdir target
	@avr-gcc -Wall -Os -mmcu=$(DEVICE) -c $(SOURCE) -o ./target/$(PROJECT).o
	@avr-gcc -Wall -Os -mmcu=$(DEVICE) -o ./target/$(PROJECT).elf ./target/$(PROJECT).o
	@avr-objcopy -j .text -j .data -O ihex ./target/$(PROJECT).elf ./target/$(PROJECT).hex
	@echo "INFO: Build finished successfully"

clean: 
	@if [ -d ./target ]; \
	then \
		rm ./target/$(PROJECT).hex ; \
		rm ./target/$(PROJECT).elf ; \
		rm ./target/$(PROJECT).o ; \
		rmdir ./target; \
		echo "INFO: Previously generated target files removed";	\
	else \
		echo "INFO: No generated target files"; \
	fi

disasm: target/$(PROJECT).elf
	avr-objdump -d target/$(PROJECT).elf

size:
	@avr-size --format=avr --mcu=$(DEVICE) ./target/$(PROJECT).elf

check:
	@avrdude -v -V  -p $(DEVICE) -c $(PROGRAMMER) -P /dev/ttyUSB0 

upload:
	@avrdude -v -V  -p $(DEVICE) -c $(PROGRAMMER) -P /dev/ttyUSB0 -b 115200 -D -U flash:w:./target/$(PROJECT).hex:i